version: '3.8'

services:
  # 配置服务器副本集
  config_node1:
    image: mongo:4.0.5
    container_name: mongo_config1
    # --configsvr: 这个参数仅仅是将默认端口由27017改为27019, 如果指定--port可不添加该参数
    command: mongod --configsvr --directoryperdb --replSet fates-mongo-config --smallfiles
    volumes:
      - /etc/localtime:/etc/localtime
      - /mongodb/config/node1/data:/data/configdb
    networks:
      - mongo

  config_node2:
    image: mongo:4.0.5
    container_name: mongo_config2
    command: mongod --configsvr --directoryperdb --replSet fates-mongo-config --smallfiles
    volumes:
      - /etc/localtime:/etc/localtime
      - /mongodb/config/node2/data:/data/configdb
    networks:
      - mongo

  config_node3:
    image: mongo:4.0.5
    container_name: mongo_config3
    command: mongod --configsvr --directoryperdb --replSet fates-mongo-config --smallfiles
    volumes:
      - /etc/localtime:/etc/localtime
      - /mongodb/config/node3/data:/data/configdb
    networks:
      - mongo

  # 分片1副本集
  shard1_node1:
    image: mongo:4.0.5
    container_name: shard1_node1
    command: mongod --shardsvr --directoryperdb --replSet shard1 --port 27018
    volumes:
      - /etc/localtime:/etc/localtime
      - /mongodb/shard1/node1/data:/data/db
    privileged: true
    mem_limit: 16000000000
    networks:
      - mongo

  shard1_node2:
    image: mongo:4.0.5
    container_name: shard1_node2
    command: mongod --shardsvr --directoryperdb --replSet shard1 --port 27118
    volumes:
      - /etc/localtime:/etc/localtime
      - /mongodb/shard1/node2/data:/data/db
    privileged: true
    mem_limit: 16000000000
    networks:
      - mongo

  shard1_node3:
    image: mongo:4.0.5
    container_name: shard1_node3
    command: mongod --shardsvr --directoryperdb --replSet shard1 --arbiter --port 27218
    volumes:
      - /etc/localtime:/etc/localtime
      - /mongodb/shard1/node3/data:/data/db
    privileged: true
    mem_limit: 16000000000
    networks:
      - mongo

  # 分片2副本集
  shard2_node1:
    image: mongo:4.0.5
    container_name: shard2_node1
    command: mongod --shardsvr --directoryperdb --replSet shard2 --port 27318
    volumes:
      - /etc/localtime:/etc/localtime
      - /mongodb/shard2/node1/data:/data/db
    privileged: true
    mem_limit: 16000000000
    networks:
      - mongo

  shard2_node2:
    image: mongo:4.0.5
    container_name: shard2_node2
    command: mongod --shardsvr --directoryperdb --replSet shard2 --port 27418
    volumes:
      - /etc/localtime:/etc/localtime
      - /mongodb/shard2/node2/data:/data/db
    privileged: true
    mem_limit: 16000000000
    networks:
      - mongo

  shard2_node3:
    image: mongo:4.0.5
    container_name: shard2_node3
    command: mongod --shardsvr --directoryperdb --replSet shard2 --arbiter --port 27518
    volumes:
      - /etc/localtime:/etc/localtime
      - /mongodb/shard2/node3/data:/data/db
    privileged: true
    mem_limit: 16000000000
    networks:
      - mongo

  # Mongos 路由器
  router_node1:
    image: mongo:4.0.5
    container_name: mongos1
    command: mongos --configdb configserver/config1:27019,config2:27020,config3:27021 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 27017:27017
    depends_on:
      - config_node1
      - config_node2
      - config_node3
    networks:
      - mongo

  router_node2:
    image: mongo:4.0.5
    container_name: mongos2
    command: mongos --configdb configserver/config1:27019,config2:27020,config3:27021 --bind_ip 0.0.0.0 --port 27117
    ports:
      - 27117:27117
    depends_on:
      - config_node1
      - config_node2
      - config_node3
    networks:
      - mongo

networks:
  mongo:
    external: true